name: Chris Swithinbank
description: Music, text, and concerts
author:
    name: Chris Swithinbank
    email: swithinbank@gmail.com
    uri: http://www.chrisswithinbank.net/
markdown: kramdown
highlighter: pygments
gems:
    - jekyll-sitemap
    - jekyll-feed
permalink: /:categories/:title
timezone: Europe/Berlin
sass:
    sass_dir: _sass
    style: compressed
collections:
  events:
    output: true
    permalink: events/:title/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: "music"
      type: "posts"
    values:
      layout: music
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: event
      locationtype: MusicVenue
      performertype: MusicGroup
