name: Chris Swithinbank
description: Music, text, and concerts
url: http://www.chrisswithinbank.net
author:
    name: Chris Swithinbank
    email: swithinbank@gmail.com
    uri: http://www.chrisswithinbank.net/
    twitter: https://twitter.com/swithinbank
    github: https://github.com/delucis
    soundcloud: https://soundcloud.com/swithinbank
markdown: kramdown
gems:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-picture-tag
permalink: /:year/:month/:title/
timezone: Europe/Berlin
sass:
    sass_dir: _sass
    style: compressed
paginate: 5
paginate_path: "/page/:num/"
paginate_per_category: true
default_category: "blog"
picture:
  source: "assets/images/_fullsize"
  output: "uploads"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2]
      source_large:
        media: "(min-width: 45em)"
        width: "538"
      source_medium:
        media: "(min-width: 22.5em)"
        width: "512"
      source_default:
        width: "324"
    sidebar:
      ppi: [1, 1.5, 2]
      source_large:
        media: "(min-width: 70em)"
        width: "350"
      source_medium:
        media: "(min-width: 22.5em)"
        width: "512"
      source_default:
        width: "324"
    alignright:
      ppi: [1, 1.5, 2]
      attr:
        class: "alignright"
      source_large:
        media: "(min-width: 45em)"
        width: "190"
      source_default:
        width: "150"
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            category: "blog"
            tags:
              - single-post
    -
        scope:
            path: "music"
            type: "posts"
        values:
            layout: "music"
            category: "music"
            tags:
              - single-music
    -
        scope:
            path: "events"
            type: "posts"
        values:
            layout: "event"
            category: "events"
            tags:
              - single-event
    -
        scope:
            path: ""
            type: "pages"
        values:
            category: "page"
