name: Chris Swithinbank
description: Music, text, and concerts
url: http://www.chrisswithinbank.net
author:
    name: Chris Swithinbank
    email: swithinbank@gmail.com
    uri: http://www.chrisswithinbank.net/
markdown: kramdown
highlighter: pygments
gems:
    - jekyll-sitemap
    - jekyll-feed
permalink: /:year/:month/:title/
timezone: Europe/Berlin
sass:
    sass_dir: _sass
    style: compressed
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: post
    -
        scope:
            path: "music"
            type: "posts"
        values:
            layout: music
            category: music
    -
        scope:
            path: "events"
            type: "posts"
        values:
            layout: event
            category: events
            locationtype: MusicVenue
            performertype: MusicGroup
