name: Chris Swithinbank
description: Music, text, and concerts
url: https://chrisswithinbank.net
author:
    name: Chris Swithinbank
    email: swithinbank@gmail.com
    uri: https://www.chrisswithinbank.net/
    twitter: swithinbank
    github: https://github.com/delucis
    soundcloud: https://soundcloud.com/swithinbank
    facebook: https://www.facebook.com/chris.swithinbank
    musicbrainz: https://musicbrainz.org/artist/f0eb2424-ad68-478b-97a8-a4d34770c10d
facebook:
  app_id: 1614752738807936
  user_id: 61411247
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-picture-tag
    - jekyll-last-modified-at
    - jekyll-sitemap
    - jekyll-paginate-v2
permalink: /:year/:month/:title/
timezone: Europe/Berlin
future: true
sass:
    sass_dir: _sass
    style: compressed
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  title: ":title /p.:num"
  limit: 0
  sort_field: 'date'
  sort_reverse: true
default_category: "blog"
exclude: [README.md, Gemfile, Gemfile.lock, netlify.toml]
picture:
  source: "wp-content/uploads"
  output: "wp-content/uploads"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2]
      attr:
        class: "picture default multiply"
      source_large:
        media: "(min-width: 45em)"
        width: "538"
      source_medium:
        media: "(min-width: 22.5em)"
        width: "512"
      source_default:
        width: "324"
    sidebar:
      ppi: [1, 1.5, 2]
      attr:
        class: "picture sidebar multiply"
      source_large:
        media: "(min-width: 70em)"
        width: "350"
      source_medium:
        media: "(min-width: 22.5em)"
        width: "512"
      source_default:
        width: "324"
    alignright:
      ppi: [1, 1.5, 2]
      attr:
        class: "picture alignright multiply"
      source_large:
        media: "(min-width: 45em)"
        width: "189"
      source_medium:
        media: "(min-width: 22.5em)"
        width: "150"
      source_default:
        width: "324"
    alignleft:
      ppi: [1, 1.5, 2]
      attr:
        class: "picture alignleft multiply"
      source_large:
        media: "(min-width: 45em)"
        width: "189"
      source_medium:
        media: "(min-width: 22.5em)"
        width: "150"
      source_default:
        width: "324"
    wide:
      ppi: [1, 1.5, 2]
      attr:
        class: "picture wide multiply"
      source_xlarge:
        media: "(min-width: 70em)"
        width: "807"
      source_large:
        media: "(min-width: 45em)"
        width: "661"
      source_medium:
        media: "(min-width: 22.5em)"
        width: "512"
      source_default:
        width: "324"
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: "blog"
            type: "posts"
        values:
            layout: "post"
            category: "blog"
            tags:
              - single-post
    -
        scope:
            path: "music"
            type: "posts"
        values:
            layout: "music"
            category: "music"
            tags:
              - single-music
    -
        scope:
            path: "events"
            type: "posts"
        values:
            layout: "event"
            category: "events"
            tags:
              - single-event
    -
        scope:
            path: "text"
            type: "posts"
        values:
            layout: "page"
            category: "text"
            tags:
              - single-text
    -
        scope:
            path: ""
            type: "pages"
        values:
            category: "page"
