[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  # Optional (but highly recommended). Defaults to [".cache"].
  paths = ["_site/wp-content/uploads"]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy-Report-Only = "default-src https:; frame-ancestors 'none'; object-src 'none'; base-uri 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection: 1; mode=block

[[headers]]
  for = "/wp-content/uploads/*"
  [headers.values]
    Cache-Control = [
      "public",
      "max-age=31536000"
    ]
